beetl:
  templates-path: templates
mqtt:
  host: tcp://localhost:1883
  username: iotweb
  password: iotweb
  qos: 1
  client-id: thermometer001
  topic:
    post: /iot/cloud/devices/post
    post_reply: /iot/cloud/devices/post_reply
    receive: /iot/cloud/devices/receive
    receive_reply: /iot/cloud/devices/receive_reply
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:iot/cloud/platform/thermometer/mapper/*Mapper.xml
  type-aliases-package: iot.cloud.platform.thermometer.domain.*
server:
  port: 8100
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/iotthermo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: iotthermo
    password: dpLJnVgnq@v7

